# Generated by Django 4.2.7 on 2023-12-11 10:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backlog", "0001_squashed_0010_alter_game_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="image",
        ),
    ]
